### PR TITLE
Feat security layer

### PR DESCRIPTION
**Pull request by tsemayess**
Security has been added to all endpoints with jwt tokens

### CODE REVIEW

**Comment by MarvinHernandezSS** [comment]
no conflicts, just need some clarity on accessing the new secure URIs

**Comment by MarvinHernandezSS** [comment]
.

**Comment by MarvinHernandezSS** [comment]
Also I did not see a 
@RequestMapping and the URI names have both plural and singular, not sure if thats intended or not.

**Comment by tsemayess** [comment]
The mix between singular and plural is intentional. If it is plural it indicates a group of restaurants will be return based upon the specified criteria and if singular then a single restaurant is being returned, created, updated, or deleted.

**Pull request merged**
